### ISSUE TITLE
Help compiling picorv32 for Basys3

### ISSUE THREAD

**Issue by kendallgreen** [tmahlburg/picosoc-basys3#1]

**Comment by kendallgreen** [comment]
I need help in compiling picorv32 for Basys3.  I have managed to download and compile the riscv tool chain,  cloned and moved your picosoc-basys3 files to the picosoc folder under picorv32.  I have successfully run make there.  However I am stuck on the 
scripts/vivado folder where it doesn't have a xc7a35t-cpg236c choice.  I don't know what to do to load this into the Basys3

**Comment by tmahlburg** [comment]
Okay, so there are two things you need to do:

1. Synthesize and flash the picosoc (the processor logic itself) onto the Basys3
2. Compile and flash your firmware (the logic you want the processor to execute) onto the Basys3 SPI flash storage

I always did the first step manually via the Vivado GUI. I might be able to build a script for this, but it would take a little while. Basically you need to create a project, where you have the `picorv32.v`, the `picosoc.v`, `simpleuart.v`, `spimemio.v` and the `basys3.v`. The `basys3.v` needs to be set as the top module. You also need to set the [constraints file](https://github.com/Digilent/Basys3/blob/master/Resources/XDC/Basys3_Master.xdc) I linked in the README. By default, every line is commented out, so you need to uncomment the ones you need (or all of them, there shouldn't be any conflicts). Now you should be able to build the bitstream and flash it to the board. (If you need help setting up Vivado and doing this step, you can look at the [Digilent documentation](https://reference.digilentinc.com/reference/programmable-logic/basys-3/start). You should flash it to the board, after you put the firmware in the SPI.

The compilation in the second step seems to be working, it is done using the Makefile in this project and expects the firmware to be in a file called `basys3_fw.c`. Then you can run
`make basys3_fw.bin`
to compile the firmware. Now you need to flash the resulting `basys3_fw.bin` file onto the flash storage of the Basys3. There is a bit old, but still good [tutorial](https://sites.google.com/a/umn.edu/mxp-fpga/home/vivado-notes/programming-the-basys3-board-through-vivado) on how to flash files onto the SPI flash.

As a last step, you flash the bitstream of step 1 onto the Basys3. Now the picosoc executes the firmware you provided.

Please note, that this was written from memory, so I didn't double-check everything, because my dev environment is not currently setup. I'm happy to set it up again, if you get stuck at any point, so feel free to ask if you need further assistance. Good luck!

**Comment by tmahlburg** [comment]
Since you seem to have figured it out, I'm going to close this. Feel free to reopen, if you are still having problems.

**Comment by kendallgreen** [comment]
No.  I had given up for the time.
